replicaCount: 1

image:
  repository: gcr.io/google-samples/gb-frontend
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  name:
podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  nodePort: 32000
  port: 80

ingress:
  enabled: false
  annotations: 
    annotated: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

redis:
  fullnameOverride: redis
  usePassword: false
  configmap: |-
    appendonly no